# Generated by Django 5.1.4 on 2025-01-02 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0002_extracteddata"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ExtractedData",
        ),
    ]
