# Generated by Django 5.1.4 on 2025-01-02 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0003_delete_extracteddata"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtractedData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_name", models.CharField(max_length=255)),
                ("field_value", models.TextField()),
            ],
        ),
    ]
