# Generated by Django 5.1.4 on 2025-01-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0004_extracteddata"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnnotatedImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_image", models.ImageField(upload_to="original_images/")),
                ("annotated_image", models.ImageField(upload_to="annotated_images/")),
                ("annotations", models.JSONField()),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="ExtractedData",
        ),
    ]
