# Generated by Django 5.1.4 on 2025-01-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0005_annotatedimage_delete_extracteddata"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotatedimage",
            name="ntn_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
